-- Cada reserva fica registrada com o correlationId da requisição que a originou.
-- Isso torna a reserva idempotente (uma requisição repetida não debita duas vezes)
-- e permite desfazê-la depois (compensação), também de forma idempotente.
CREATE TABLE reserva (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correlation_id VARCHAR(64)              NOT NULL UNIQUE,
    produto_id     BIGINT                   NOT NULL REFERENCES produto (id),
    quantidade     INTEGER                  NOT NULL CHECK (quantidade > 0),
    status         VARCHAR(20)              NOT NULL,
    criada_em      TIMESTAMP WITH TIME ZONE NOT NULL,
    liberada_em    TIMESTAMP WITH TIME ZONE
);
