-- Modelo de dados da Etapa 6, com reforços:
--   pedido_id UNIQUE: o RabbitMQ garante entrega "pelo menos uma vez", então o mesmo
--     evento pode chegar duas vezes. A restrição impede cobrar o mesmo pedido duas vezes
--     (consumidor idempotente), mesmo com duas instâncias do serviço (Etapa 10).
--   correlation_id: rastreabilidade ponta a ponta (Etapa 11).
--   instancia: hostname do contêiner que processou o pagamento (evidência da Etapa 10).
-- pedido_id NÃO é chave estrangeira: o pedido vive no banco do Pedido Service.
CREATE TABLE pagamento (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id      BIGINT                   NOT NULL UNIQUE,
    status         VARCHAR(50)              NOT NULL,
    correlation_id VARCHAR(64)              NOT NULL,
    instancia      VARCHAR(100)             NOT NULL,
    processado_em  TIMESTAMP WITH TIME ZONE NOT NULL
);
