-- Modelo de dados da Etapa 2, com duas colunas a mais:
--   correlation_id: liga o pedido aos logs dos três serviços e à reserva no Estoque;
--   criado_em/atualizado_em: permitem reconstruir a linha do tempo de um incidente.
-- produto_id NÃO tem chave estrangeira: o produto vive no banco do Estoque Service,
-- e um banco não pode referenciar o banco de outro serviço (banco por serviço).
CREATE TABLE pedido (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id     BIGINT                   NOT NULL,
    quantidade     INTEGER                  NOT NULL CHECK (quantidade > 0),
    status         VARCHAR(50)              NOT NULL,
    correlation_id VARCHAR(64)              NOT NULL UNIQUE,
    criado_em      TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em  TIMESTAMP WITH TIME ZONE NOT NULL
);
