-- Transactional Outbox: o evento pedido.criado é gravado NA MESMA transação local que
-- cria o pedido. Um relay lê os eventos PENDENTES e os publica no RabbitMQ. Assim, nunca
-- existe pedido sem evento (nem evento sem pedido), mesmo que o broker esteja fora do ar
-- ou o processo caia entre o commit no banco e a publicação.
CREATE TABLE outbox_evento (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id      BIGINT                   NOT NULL REFERENCES pedido (id),
    exchange       VARCHAR(100)             NOT NULL,
    routing_key    VARCHAR(100)             NOT NULL,
    payload        TEXT                     NOT NULL,
    correlation_id VARCHAR(64)              NOT NULL,
    status         VARCHAR(20)              NOT NULL,
    tentativas     INTEGER                  NOT NULL DEFAULT 0,
    criado_em      TIMESTAMP WITH TIME ZONE NOT NULL,
    publicado_em   TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_outbox_evento_status ON outbox_evento (status, id);
